"use strict";var L=(n,t,e)=>{if(!t.has(n))throw TypeError("Cannot "+e)};var i=(n,t,e)=>(L(n,t,"read from private field"),e?e.call(n):t.get(n)),p=(n,t,e)=>{if(t.has(n))throw TypeError("Cannot add the same private member more than once");t instanceof WeakSet?t.add(n):t.set(n,e)},d=(n,t,e,s)=>(L(n,t,"write to private field"),s?s.call(n,e):t.set(n,e),e);Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"});const P=require("../custom-element/index.cjs"),$=require("../string-vBu90jhV.cjs");var w,h,f;class T{constructor(t){p(this,w,void 0);p(this,h,void 0);p(this,f,void 0);d(this,w,t.index),d(this,h,document.createElement("span")),d(this,f,[]),t.letters&&t.letterConstructor&&t.lettersAcc!==void 0?(d(this,f,t.text.split("").map((e,s)=>new t.letterConstructor({index:t.lettersAcc+s,text:e,clone:t.clone}))),i(this,h).append(...i(this,f).map(e=>e.element))):t.clone?i(this,h).innerHTML=`
          <span class="original">${t.text}</span>
          <span class="clone" aria-hidden>${t.text}</span>
        `:i(this,h).innerHTML=`
          <span class="value">${t.text}</span>
        `,i(this,h).classList.add("word")}get index(){return i(this,w)}get element(){return i(this,h)}get letters(){return i(this,f)}}w=new WeakMap,h=new WeakMap,f=new WeakMap;var C,a;class S{constructor(t){p(this,C,void 0);p(this,a,void 0);d(this,C,t.index),d(this,a,document.createElement("span")),i(this,a).classList.add("letter"),t.clone?i(this,a).innerHTML=`
        <span class="original">${t.text}</span>
        <span class="clone" aria-hidden>${t.text}</span>
      `:i(this,a).innerHTML=`
        <span class="value">${t.text}</span>
      `}get index(){return i(this,C)}get element(){return i(this,a)}}C=new WeakMap,a=new WeakMap;var D=Object.defineProperty,O=Object.getOwnPropertyDescriptor,W=(n,t,e,s)=>{for(var r=s>1?void 0:s?O(t,e):t,l=n.length-1,u;l>=0;l--)(u=n[l])&&(r=(s?u(t,e,r):u(r))||r);return s&&r&&D(t,e,r),r},A=(n,t,e)=>{if(!t.has(n))throw TypeError("Cannot "+e)},o=(n,t,e)=>(A(n,t,"read from private field"),e?e.call(n):t.get(n)),_=(n,t,e)=>{if(t.has(n))throw TypeError("Cannot add the same private member more than once");t instanceof WeakSet?t.add(n):t.set(n,e)},y=(n,t,e,s)=>(A(n,t,"write to private field"),s?s.call(n,e):t.set(n,e),e),g,c,x,E,M;exports.SlicerElement=class extends P.CustomElement{constructor(t){super(),_(this,g,""),_(this,c,[]),_(this,x,[]),_(this,E,void 0),_(this,M,void 0),y(this,E,(t==null?void 0:t.wordConstructor)||T),y(this,M,(t==null?void 0:t.letterConstructor)||S)}get wordsArray(){return o(this,c)}get lettersArray(){return o(this,x)}get originalText(){return o(this,g)}connectedCallback(){var e;y(this,g,((e=this.textContent)==null?void 0:e.trim())||""),this.innerHTML="";let t=0;y(this,c,o(this,g).replace(/  +/g," ").split(" ").map((s,r)=>{const l=new(o(this,E))({index:r,text:s,letters:this.hasAttribute("letters"),lettersAcc:t,letterConstructor:o(this,M),clone:this.hasAttribute("clone")});return t+=l.letters.length,o(this,x).push(...l.letters),l})),this.hasAttribute("index")&&(o(this,c).forEach(s=>{s.element.style.setProperty("--word-index",s.index.toString())}),o(this,x).forEach(s=>{s.element.style.setProperty("--letter-index",s.index.toString())})),o(this,c).forEach((s,r)=>{if(this.appendChild(s.element),r!==o(this,c).length-1){const l=document.createElement("span");l.innerHTML="&nbsp;",this.appendChild(l)}}),this.style.setProperty("--words-length",o(this,c).length.toString()),this.style.setProperty("--letters-length",o(this,x).length.toString())}disconnectedCallback(){y(this,c,[]),this.textContent=o(this,g),this.style.removeProperty("--words-length"),this.style.removeProperty("--letters-length")}};g=new WeakMap;c=new WeakMap;x=new WeakMap;E=new WeakMap;M=new WeakMap;exports.SlicerElement=W([P.define("e-slicer")],exports.SlicerElement);var m=Object.defineProperty,H=Object.getOwnPropertyDescriptor,b=(n,t,e,s)=>{for(var r=s>1?void 0:s?H(t,e):t,l=n.length-1,u;l>=0;l--)(u=n[l])&&(r=(s?u(t,e,r):u(r))||r);return s&&r&&m(t,e,r),r},v;class q extends S{constructor(e){super(e);p(this,v,void 0);d(this,v,$.generateId(2+Math.floor(Math.random()*15),"abcdefghijklmnopqrstuvwxyz0123456789#!%$^&*+=?")+e.text),this.play(0)}play(e){const s=Math.floor(e*(i(this,v).length-1));this.element.textContent=i(this,v)[s]}}v=new WeakMap;exports.DecoderElement=class extends exports.SlicerElement{constructor(){super({letterConstructor:q})}play(t){this.lettersArray.forEach(e=>{e.play(t)})}};exports.DecoderElement=b([P.define("e-decoder")],exports.DecoderElement);exports.Letter=S;exports.Word=T;
