"use strict";var M=(n,t,e)=>{if(!t.has(n))throw TypeError("Cannot "+e)};var s=(n,t,e)=>(M(n,t,"read from private field"),e?e.call(n):t.get(n)),l=(n,t,e)=>{if(t.has(n))throw TypeError("Cannot add the same private member more than once");t instanceof WeakSet?t.add(n):t.set(n,e)},i=(n,t,e,o)=>(M(n,t,"write to private field"),o?o.call(n,e):t.set(n,e),e);Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"});const A=require("../string-DhgS_iFl.cjs");var p,h,u;class T{constructor(t){l(this,p,void 0);l(this,h,void 0);l(this,u,void 0);i(this,p,t.index),i(this,h,document.createElement("span")),i(this,u,[]),t.letters&&t.letterConstructor&&t.lettersAcc!==void 0?(i(this,u,t.text.split("").map((e,o)=>new t.letterConstructor({index:t.lettersAcc+o,text:e,clone:t.clone}))),s(this,h).append(...s(this,u).map(e=>e.element))):t.clone?s(this,h).innerHTML=`
          <span class="original">${t.text}</span>
          <span class="clone" aria-hidden>${t.text}</span>
        `:s(this,h).innerHTML=`
          <span class="value">${t.text}</span>
        `,s(this,h).classList.add("word")}get index(){return s(this,p)}get element(){return s(this,h)}get letters(){return s(this,u)}}p=new WeakMap,h=new WeakMap,u=new WeakMap;var f,d;class L{constructor(t){l(this,f,void 0);l(this,d,void 0);i(this,f,t.index),i(this,d,document.createElement("span")),s(this,d).classList.add("letter"),t.clone?s(this,d).innerHTML=`
        <span class="original">${t.text}</span>
        <span class="clone" aria-hidden>${t.text}</span>
      `:s(this,d).innerHTML=`
        <span class="value">${t.text}</span>
      `}get index(){return s(this,f)}get element(){return s(this,d)}}f=new WeakMap,d=new WeakMap;var g,r,x,E,C;class w extends HTMLElement{constructor(e){super();l(this,g,"");l(this,r,[]);l(this,x,[]);l(this,E,void 0);l(this,C,void 0);i(this,E,(e==null?void 0:e.wordConstructor)||T),i(this,C,(e==null?void 0:e.letterConstructor)||L)}get wordsArray(){return s(this,r)}get lettersArray(){return s(this,x)}get originalText(){return s(this,g)}connectedCallback(){var o;i(this,g,((o=this.textContent)==null?void 0:o.trim())||""),this.innerHTML="";let e=0;i(this,r,s(this,g).replace(/  +/g," ").split(" ").map((c,m)=>{const a=new(s(this,E))({index:m,text:c,letters:this.hasAttribute("letters"),lettersAcc:e,letterConstructor:s(this,C),clone:this.hasAttribute("clone")});return e+=a.letters.length,s(this,x).push(...a.letters),a})),this.hasAttribute("index")&&(s(this,r).forEach(c=>{c.element.style.setProperty("--word-index",c.index.toString())}),s(this,x).forEach(c=>{c.element.style.setProperty("--letter-index",c.index.toString())})),s(this,r).forEach((c,m)=>{if(this.appendChild(c.element),m!==s(this,r).length-1){const a=document.createElement("span");a.innerHTML="&nbsp;",this.appendChild(a)}}),this.style.setProperty("--words-length",s(this,r).length.toString()),this.style.setProperty("--letters-length",s(this,x).length.toString())}disconnectedCallback(){i(this,r,[]),this.textContent=s(this,g),this.style.removeProperty("--words-length"),this.style.removeProperty("--letters-length")}}g=new WeakMap,r=new WeakMap,x=new WeakMap,E=new WeakMap,C=new WeakMap;customElements.get("e-slicer")||customElements.define("e-slicer",w);var y;class S extends L{constructor(e){super(e);l(this,y,void 0);i(this,y,A.generateId(2+Math.floor(Math.random()*15),"abcdefghijklmnopqrstuvwxyz0123456789#!%$^&*+=?")+e.text),this.play(0)}play(e){const o=Math.floor(e*(s(this,y).length-1));this.element.textContent=s(this,y)[o]}}y=new WeakMap;class b extends w{constructor(){super({letterConstructor:S})}play(t){this.lettersArray.forEach(e=>{e.play(t)})}}customElements.get("e-decoder")||customElements.define("e-decoder",b);exports.DecoderElement=b;exports.Letter=L;exports.SlicerElement=w;exports.Word=T;
