name: 'publish npm'

on:
  push:
    branches: ['main']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: Build libs
        run: npm run build:libs
      - name: Upload client-lib
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./client-lib
      - name: Upload server-lib
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./server-lib
      - name: Publish package
        run: npm publish --access public
        working-directory: ./
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
